{
 "title": "Eventify dashboard",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values({__name__=~\"dotnet_assembly_count\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"dotnet_assembly_count\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ASP.NET Core [$job]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{http_route!=\"/metrics\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency (p50, p95, p99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": ".NET GC and Memory [$job]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": ".NET GC Pause Time",
     "type": "timeseries",
     "description": "Total amount of seconds the GC was paused in each process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job) (irate(dotnet_gc_pause_time_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range])) or sum by (job) (irate(process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\"$job\",instance=~\"$instance\"}[$__range]) / 1e9)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": ".NET GC Collection Attempts",
     "type": "timeseries",
     "description": "Number of GC collection attempts per generation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "collections" } },
     "targets": [
      {
       "expr": "sum by (job, gc_heap_generation) (ceil(irate({__name__=~\"dotnet_gc_collections_total|process_runtime_dotnet_gc_collections_count_total\", job=~\"$job\", instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{job}} - {{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": ".NET GC Memory Committed",
     "type": "timeseries",
     "description": "The amount of physical memory in-use inside each .NET process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job) ({__name__=~\"dotnet_gc_last_collection_memory_committed_size_bytes|process_runtime_dotnet_gc_committed_memory_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{job}} - {{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": ".NET GC Heap Fragmentation",
     "type": "timeseries",
     "description": "Memory fragmentation in the managed heap, per-GC generation.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job, gc_heap_generation) ({__name__=~\"dotnet_gc_last_collection_heap_fragmentation_size_bytes|process_runtime_dotnet_gc_heap_fragmentation_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{job}} - {{gc_heap_generation}}"
      }
     ]
    },
    {
     "title": ".NET GC Last Collection Heap Size",
     "type": "timeseries",
     "description": "The size of each of the managed heaps, following their last GC collection attempt.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (job, gc_heap_generation) ({__name__=~\"dotnet_gc_last_collection_heap_size_bytes|process_runtime_dotnet_gc_heap_size_bytes\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{job}} - {{gc_heap_generation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU and ThreadPool [$job]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": ".NET ThreadPool Workload",
     "type": "timeseries",
     "description": "Number of work items completed by the .NET managed ThreadPool on this [$job]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "items" } },
     "targets": [
      {
       "expr": "sum by (job) (floor(irate({__name__=~\"dotnet_thread_pool_work_item_count_total|process_runtime_dotnet_thread_pool_completed_items_count_total\", job=~\"$job\",instance=~\"$instance\"}[$__range])))",
       "legendFormat": "{{job}} completed items"
      }
     ]
    },
    {
     "title": ".NET ThreadPool Threads and Timers",
     "type": "timeseries",
     "description": "Number of .NET ThreadPool threads and timers on [$job]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "threads" } },
     "targets": [
      {
       "expr": "sum by(job) ({__name__=~\"dotnet_thread_pool_thread_count_total|process_runtime_dotnet_thread_pool_threads_count\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{job}} threads"
      },
      {
       "expr": "sum by(job) ({__name__=~\"dotnet_timer_count|process_runtime_dotnet_timer_count\", job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "{{job}} timers"
      }
     ]
    },
    {
     "title": "CPU Seconds by Job",
     "type": "timeseries",
     "description": "⚠️ Requires .NET 9+ built-in metrics (not available in OpenTelemetry.Instrumentation.Runtime package for .NET 6/7/8).\n\nThe amount of CPU time used by instances of [$job]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (job, cpu_mode) (irate(dotnet_process_cpu_time_seconds_total{job=~\"$job\"}[$__range]))",
       "legendFormat": "{{job}} [{{cpu_mode}}]"
      }
     ]
    },
    {
     "title": "Available CPUs",
     "type": "table",
     "description": "⚠️ Requires .NET 9+ built-in metrics (not available in OpenTelemetry.Instrumentation.Runtime package for .NET 6/7/8).\n\nAll logical CPUs available to this process - these are shared with other processes running on the same machine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Logical CPUs" } },
     "targets": [
      {
       "expr": "sum by(job, instance) (dotnet_process_cpu_count{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}/{{job}} CPU"
      }
     ]
    }
   ]
  }
 ]
}