<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ya.Events.Application\Ya.Events.Application.csproj" />
    <ProjectReference Include="..\Ya.Events.Infrastructure\Ya.Events.Infrastructure.csproj" />
  </ItemGroup>

</Project>
